// <auto-generated />
using System;
using ApplicationSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignacion", b =>
                {
                    b.Property<string>("IdAsignacion")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignacion");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dia");

                    b.Property<string>("Escenario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ING_DIURNA")
                        .HasColumnName("escenario");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Propuesta")
                        .HasColumnName("estado");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("IdAsignatura")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<string>("IdDocente")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdDocente");

                    b.ToTable("asignaciones", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignatura", b =>
                {
                    b.Property<string>("IdAsignatura")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<string>("Aula")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("aula");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creditos");

                    b.Property<bool>("EsAreaProfesional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("es_area_profesional");

                    b.Property<bool>("EsFijaTapsi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("es_fija_tapsi");

                    b.Property<bool>("EsOpcionalTapsiDiurna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("es_opcional_tapsi_diurna");

                    b.Property<string>("IdPlan")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_plan");

                    b.Property<int>("MinEstudiantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(15)
                        .HasColumnName("min_estudiantes");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semestre");

                    b.HasKey("IdAsignatura");

                    b.HasIndex("IdPlan");

                    b.HasIndex("Codigo", "IdPlan")
                        .IsUnique();

                    b.ToTable("asignaturas", (string)null);

                    b.HasData(
                        new
                        {
                            IdAsignatura = "a1000001-a100-a100-a100-a10000000000",
                            Aula = "AULA-F101",
                            Codigo = "104066",
                            Creditos = 4,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Matemáticas Básicas",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000002-a100-a100-a100-a10000000000",
                            Aula = "AULA-F102",
                            Codigo = "100010",
                            Creditos = 2,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Fundamentos de Ingeniería",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000003-a100-a100-a100-a10000000000",
                            Aula = "AULA-F103",
                            Codigo = "103004",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Teoría de Sistemas",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000004-a100-a100-a100-a10000000000",
                            Aula = "AULA-F104",
                            Codigo = "103002",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Lógica de Programación",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000005-a100-a100-a100-a10000000000",
                            Aula = "AULA-F105",
                            Codigo = "100059",
                            Creditos = 3,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Competencias Comunicativas",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000006-a100-a100-a100-a10000000000",
                            Aula = "AULA-F106",
                            Codigo = "105038",
                            Creditos = 2,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Ética",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000007-a100-a100-a100-a10000000000",
                            Aula = "AULA-F107",
                            Codigo = "151601",
                            Creditos = 1,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Inglés I",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a1000008-a100-a100-a100-a10000000000",
                            Aula = "AULA-F108",
                            Codigo = "103007",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Técnicas de Programación",
                            Semestre = 2
                        },
                        new
                        {
                            IdAsignatura = "a1000009-a100-a100-a100-a10000000000",
                            Aula = "AULA-F109",
                            Codigo = "103008",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Fundamentos de POO",
                            Semestre = 2
                        },
                        new
                        {
                            IdAsignatura = "a1000010-a100-a100-a100-a10000000000",
                            Aula = "AULA-F110",
                            Codigo = "104027",
                            Creditos = 4,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Matemáticas Discretas",
                            Semestre = 3
                        },
                        new
                        {
                            IdAsignatura = "a1000011-a100-a100-a100-a10000000000",
                            Aula = "AULA-F111",
                            Codigo = "103011",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Estructura de Datos",
                            Semestre = 3
                        },
                        new
                        {
                            IdAsignatura = "a1000012-a100-a100-a100-a10000000000",
                            Aula = "AULA-F112",
                            Codigo = "103018",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Programación Orientada a Objetos",
                            Semestre = 3
                        },
                        new
                        {
                            IdAsignatura = "a1000013-a100-a100-a100-a10000000000",
                            Aula = "AULA-F113",
                            Codigo = "103027",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas Operativos",
                            Semestre = 4
                        },
                        new
                        {
                            IdAsignatura = "a1000014-a100-a100-a100-a10000000000",
                            Aula = "AULA-F114",
                            Codigo = "109180",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Bases de Datos I",
                            Semestre = 4
                        },
                        new
                        {
                            IdAsignatura = "a1000015-a100-a100-a100-a10000000000",
                            Aula = "AULA-F115",
                            Codigo = "103022",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Ingeniería de Software I",
                            Semestre = 4
                        },
                        new
                        {
                            IdAsignatura = "a1000016-a100-a100-a100-a10000000000",
                            Aula = "AULA-F116",
                            Codigo = "109182",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Paradigmas de Lenguajes",
                            Semestre = 5
                        },
                        new
                        {
                            IdAsignatura = "a1000017-a100-a100-a100-a10000000000",
                            Aula = "AULA-F117",
                            Codigo = "103126",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Redes LAN",
                            Semestre = 5
                        },
                        new
                        {
                            IdAsignatura = "a1000018-a100-a100-a100-a10000000000",
                            Aula = "AULA-F118",
                            Codigo = "103093",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Ingeniería de Software II",
                            Semestre = 5
                        },
                        new
                        {
                            IdAsignatura = "a1000019-a100-a100-a100-a10000000000",
                            Aula = "AULA-F119",
                            Codigo = "109183",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Programación Backend",
                            Semestre = 5
                        },
                        new
                        {
                            IdAsignatura = "a1000020-a100-a100-a100-a10000000000",
                            Aula = "AULA-F120",
                            Codigo = "109184",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Electrónica Digital y Arq. Computadores",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a1000021-a100-a100-a100-a10000000000",
                            Aula = "AULA-F121",
                            Codigo = "109185",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Modelamiento y Simulación",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a1000022-a100-a100-a100-a10000000000",
                            Aula = "AULA-F122",
                            Codigo = "109186",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Procesadores de Lenguajes",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a1000023-a100-a100-a100-a10000000000",
                            Aula = "AULA-F123",
                            Codigo = "109187",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Programación Frontend",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a1000024-a100-a100-a100-a10000000000",
                            Aula = "AULA-F124",
                            Codigo = "103021",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Diseño de Algoritmos",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a1000025-a100-a100-a100-a10000000000",
                            Aula = "AULA-F125",
                            Codigo = "109104",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas Embebidos",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a1000026-a100-a100-a100-a10000000000",
                            Aula = "AULA-F126",
                            Codigo = "103127",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Énfasis Profesional",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a1000027-a100-a100-a100-a10000000000",
                            Aula = "AULA-F127",
                            Codigo = "109188",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Ciencia de los Datos",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a1000028-a100-a100-a100-a10000000000",
                            Aula = "AULA-F128",
                            Codigo = "109181",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Bases de Datos II",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a1000029-a100-a100-a100-a10000000000",
                            Aula = "AULA-F129",
                            Codigo = "103125",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas de Información y Organizaciones",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a1000030-a100-a100-a100-a10000000000",
                            Aula = "AULA-F130",
                            Codigo = "103117",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Inteligencia Artificial",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a1000031-a100-a100-a100-a10000000000",
                            Aula = "AULA-F131",
                            Codigo = "109189",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Programación de Dispositivos Móviles",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a1000032-a100-a100-a100-a10000000000",
                            Aula = "AULA-F132",
                            Codigo = "103135",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Proyecto de Desarrollo de Software",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a1000033-a100-a100-a100-a10000000000",
                            Aula = "AULA-F133",
                            Codigo = "103136",
                            Creditos = 9,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Práctica Empresarial",
                            Semestre = 10
                        },
                        new
                        {
                            IdAsignatura = "a1000034-a100-a100-a100-a10000000000",
                            Aula = "AULA-F134",
                            Codigo = "103118",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            MinEstudiantes = 15,
                            Nombre = "Gerencia de Proyectos Tecnológicos",
                            Semestre = 10
                        },
                        new
                        {
                            IdAsignatura = "a2000001-a200-a200-a200-a20000000000",
                            Aula = "AULA-F201",
                            Codigo = "104066",
                            Creditos = 4,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Matemáticas Básicas",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a2000002-a200-a200-a200-a20000000000",
                            Aula = "AULA-F202",
                            Codigo = "100010",
                            Creditos = 2,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Fundamentos de Ingeniería",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a2000003-a200-a200-a200-a20000000000",
                            Aula = "AULA-F203",
                            Codigo = "104029",
                            Creditos = 3,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Álgebra Lineal",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a2000004-a200-a200-a200-a20000000000",
                            Aula = "AULA-F204",
                            Codigo = "103002",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Lógica de Programación",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a2000005-a200-a200-a200-a20000000000",
                            Aula = "AULA-F205",
                            Codigo = "105038",
                            Creditos = 2,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Ética",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a2000006-a200-a200-a200-a20000000000",
                            Aula = "AULA-F206",
                            Codigo = "151601",
                            Creditos = 1,
                            EsAreaProfesional = false,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Inglés I",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a2000007-a200-a200-a200-a20000000000",
                            Aula = "AULA-F207",
                            Codigo = "103004",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Teoría de Sistemas",
                            Semestre = 2
                        },
                        new
                        {
                            IdAsignatura = "a2000008-a200-a200-a200-a20000000000",
                            Aula = "AULA-F208",
                            Codigo = "103007",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Técnicas de Programación",
                            Semestre = 2
                        },
                        new
                        {
                            IdAsignatura = "a2000009-a200-a200-a200-a20000000000",
                            Aula = "AULA-F209",
                            Codigo = "103008",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Fundamentos de POO",
                            Semestre = 2
                        },
                        new
                        {
                            IdAsignatura = "a2000010-a200-a200-a200-a20000000000",
                            Aula = "AULA-F210",
                            Codigo = "104027",
                            Creditos = 4,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Matemáticas Discretas",
                            Semestre = 3
                        },
                        new
                        {
                            IdAsignatura = "a2000011-a200-a200-a200-a20000000000",
                            Aula = "AULA-F211",
                            Codigo = "103018",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Programación Orientada a Objetos",
                            Semestre = 3
                        },
                        new
                        {
                            IdAsignatura = "a2000012-a200-a200-a200-a20000000000",
                            Aula = "AULA-F212",
                            Codigo = "103011",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Estructura de Datos",
                            Semestre = 4
                        },
                        new
                        {
                            IdAsignatura = "a2000013-a200-a200-a200-a20000000000",
                            Aula = "AULA-F213",
                            Codigo = "103022",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Ingeniería de Software I",
                            Semestre = 4
                        },
                        new
                        {
                            IdAsignatura = "a2000014-a200-a200-a200-a20000000000",
                            Aula = "AULA-F214",
                            Codigo = "109180",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Bases de Datos I",
                            Semestre = 5
                        },
                        new
                        {
                            IdAsignatura = "a2000015-a200-a200-a200-a20000000000",
                            Aula = "AULA-F215",
                            Codigo = "109184",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Electrónica Digital y Arq. Computadores",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a2000016-a200-a200-a200-a20000000000",
                            Aula = "AULA-F216",
                            Codigo = "109182",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Paradigmas de Lenguajes",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a2000017-a200-a200-a200-a20000000000",
                            Aula = "AULA-F217",
                            Codigo = "103126",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Redes LAN",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a2000018-a200-a200-a200-a20000000000",
                            Aula = "AULA-F218",
                            Codigo = "109183",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Programación Backend",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a2000019-a200-a200-a200-a20000000000",
                            Aula = "AULA-F219",
                            Codigo = "103027",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas Operativos",
                            Semestre = 6
                        },
                        new
                        {
                            IdAsignatura = "a2000020-a200-a200-a200-a20000000000",
                            Aula = "AULA-F220",
                            Codigo = "109104",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas Embebidos",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a2000021-a200-a200-a200-a20000000000",
                            Aula = "AULA-F221",
                            Codigo = "109186",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Procesadores de Lenguajes",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a2000022-a200-a200-a200-a20000000000",
                            Aula = "AULA-F222",
                            Codigo = "109185",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Modelamiento y Simulación",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a2000023-a200-a200-a200-a20000000000",
                            Aula = "AULA-F223",
                            Codigo = "109187",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Programación Frontend",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a2000024-a200-a200-a200-a20000000000",
                            Aula = "AULA-F224",
                            Codigo = "103093",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Ingeniería de Software II",
                            Semestre = 7
                        },
                        new
                        {
                            IdAsignatura = "a2000025-a200-a200-a200-a20000000000",
                            Aula = "AULA-F225",
                            Codigo = "109188",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Ciencia de los Datos",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a2000026-a200-a200-a200-a20000000000",
                            Aula = "AULA-F226",
                            Codigo = "103021",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Diseño de Algoritmos",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a2000027-a200-a200-a200-a20000000000",
                            Aula = "AULA-F227",
                            Codigo = "109181",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Bases de Datos II",
                            Semestre = 8
                        },
                        new
                        {
                            IdAsignatura = "a2000028-a200-a200-a200-a20000000000",
                            Aula = "AULA-F228",
                            Codigo = "103127",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Énfasis Profesional",
                            Semestre = 9
                        },
                        new
                        {
                            IdAsignatura = "a2000029-a200-a200-a200-a20000000000",
                            Aula = "AULA-F229",
                            Codigo = "109189",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Programación de Dispositivos Móviles",
                            Semestre = 9
                        },
                        new
                        {
                            IdAsignatura = "a2000030-a200-a200-a200-a20000000000",
                            Aula = "AULA-F230",
                            Codigo = "103135",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Proyecto de Desarrollo de Software",
                            Semestre = 9
                        },
                        new
                        {
                            IdAsignatura = "a2000031-a200-a200-a200-a20000000000",
                            Aula = "AULA-F231",
                            Codigo = "103125",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas de Información y Organizaciones",
                            Semestre = 10
                        },
                        new
                        {
                            IdAsignatura = "a2000032-a200-a200-a200-a20000000000",
                            Aula = "AULA-F232",
                            Codigo = "103117",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Inteligencia Artificial",
                            Semestre = 10
                        },
                        new
                        {
                            IdAsignatura = "a2000033-a200-a200-a200-a20000000000",
                            Aula = "AULA-F233",
                            Codigo = "103118",
                            Creditos = 2,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Gerencia de Proyectos Tecnológicos",
                            Semestre = 12
                        },
                        new
                        {
                            IdAsignatura = "a2000034-a200-a200-a200-a20000000000",
                            Aula = "AULA-F234",
                            Codigo = "103136",
                            Creditos = 9,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            MinEstudiantes = 15,
                            Nombre = "Práctica Empresarial",
                            Semestre = 12
                        },
                        new
                        {
                            IdAsignatura = "a3000001-a300-a300-a300-a30000000000",
                            Aula = "AULA-F301",
                            Codigo = "104030",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Cálculo Diferencial",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000002-a300-a300-a300-a30000000000",
                            Aula = "AULA-F302",
                            Codigo = "103007",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Técnicas de Programación",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000003-a300-a300-a300-a30000000000",
                            Aula = "AULA-F303",
                            Codigo = "103018",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Programación Orientada a Objetos",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000004-a300-a300-a300-a30000000000",
                            Aula = "AULA-F304",
                            Codigo = "103004",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Teoría de Sistemas",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000005-a300-a300-a300-a30000000000",
                            Aula = "AULA-F305",
                            Codigo = "103027",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas Operativos",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000006-a300-a300-a300-a30000000000",
                            Aula = "AULA-F306",
                            Codigo = "103093",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = true,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Ingeniería de Software II",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000007-a300-a300-a300-a30000000000",
                            Aula = "AULA-F307",
                            Codigo = "103126",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = true,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Redes LAN",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a3000008-a300-a300-a300-a30000000000",
                            Aula = "AULA-F308",
                            Codigo = "109183",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = false,
                            EsOpcionalTapsiDiurna = true,
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            MinEstudiantes = 15,
                            Nombre = "Programación Backend",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a4000001-a400-a400-a400-a40000000000",
                            Aula = "AULA-F401",
                            Codigo = "104030",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "44444444-4444-4444-4444-444444444444",
                            MinEstudiantes = 15,
                            Nombre = "Cálculo Diferencial",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a4000002-a400-a400-a400-a40000000000",
                            Aula = "AULA-F402",
                            Codigo = "103007",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "44444444-4444-4444-4444-444444444444",
                            MinEstudiantes = 15,
                            Nombre = "Técnicas de Programación",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a4000003-a400-a400-a400-a40000000000",
                            Aula = "AULA-F403",
                            Codigo = "103018",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "44444444-4444-4444-4444-444444444444",
                            MinEstudiantes = 15,
                            Nombre = "Programación Orientada a Objetos",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a4000004-a400-a400-a400-a40000000000",
                            Aula = "AULA-F404",
                            Codigo = "103004",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "44444444-4444-4444-4444-444444444444",
                            MinEstudiantes = 15,
                            Nombre = "Teoría de Sistemas",
                            Semestre = 1
                        },
                        new
                        {
                            IdAsignatura = "a4000005-a400-a400-a400-a40000000000",
                            Aula = "AULA-F405",
                            Codigo = "103027",
                            Creditos = 3,
                            EsAreaProfesional = true,
                            EsFijaTapsi = true,
                            EsOpcionalTapsiDiurna = false,
                            IdPlan = "44444444-4444-4444-4444-444444444444",
                            MinEstudiantes = 15,
                            Nombre = "Sistemas Operativos",
                            Semestre = 1
                        });
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.BloqueoFranjaAsignatura", b =>
                {
                    b.Property<string>("IdBloqueo")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_bloqueo");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dia");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("IdAsignatura")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.HasKey("IdBloqueo");

                    b.HasIndex("IdAsignatura", "Periodo", "Dia", "HoraInicio", "HoraFin")
                        .IsUnique();

                    b.ToTable("bloqueos_franja_asignatura", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Disponibilidad", b =>
                {
                    b.Property<string>("IdDisponibilidad")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_disponibilidad");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dia_semana");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("IdDocente")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.HasKey("IdDisponibilidad");

                    b.HasIndex("IdDocente");

                    b.ToTable("disponibilidad", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Docente", b =>
                {
                    b.Property<string>("IdDocente")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("identificacion");

                    b.Property<int>("MaxAsignaturas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_asignaturas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_contrato");

                    b.HasKey("IdDocente");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("docentes", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.DocenteHabilitado", b =>
                {
                    b.Property<string>("IdDocente")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.Property<string>("IdAsignatura")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<DateTime>("FechaHabilitacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_habilitacion");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Excel")
                        .HasColumnName("fuente");

                    b.HasKey("IdDocente", "IdAsignatura");

                    b.HasIndex("IdAsignatura");

                    b.ToTable("docentes_habilitados", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.PlanEstudio", b =>
                {
                    b.Property<string>("IdPlan")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_plan");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("jornada");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_plan");

                    b.HasKey("IdPlan");

                    b.ToTable("planes_estudio", (string)null);

                    b.HasData(
                        new
                        {
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            Jornada = "Diurna",
                            NombrePlan = "Plan de Estudios 1020 Jornada Diurna"
                        },
                        new
                        {
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            Jornada = "Nocturna",
                            NombrePlan = "Plan de Estudios 1030 Jornada Nocturna"
                        },
                        new
                        {
                            IdPlan = "33333333-3333-3333-3333-333333333333",
                            Jornada = "Diurna",
                            NombrePlan = "Plan TAPSI Jornada Diurna"
                        },
                        new
                        {
                            IdPlan = "44444444-4444-4444-4444-444444444444",
                            Jornada = "Nocturna",
                            NombrePlan = "Plan TAPSI Jornada Nocturna"
                        });
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Coordinador"
                        });
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("correo");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = "11111111-1111-1111-1111-111111111111",
                            Correo = "admin@universidad.edu",
                            IdRol = 1,
                            NombreCompleto = "Administrador Principal",
                            PasswordHash = "$2a$11$lQyp9rSox1qD4rA177buV.ZqN7e7pFRBz9k3WUahbbpjoBmPPWCQ6"
                        });
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationSchedule.Domain.Entities.Docente", "Docente")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignatura", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.PlanEstudio", "PlanEstudio")
                        .WithMany("Asignaturas")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanEstudio");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.BloqueoFranjaAsignatura", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("BloqueosFranja")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Disponibilidad", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Docente", "Docente")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.DocenteHabilitado", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("DocentesHabilitados")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationSchedule.Domain.Entities.Docente", "Docente")
                        .WithMany("AsignaturasHabilitadas")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignatura", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("BloqueosFranja");

                    b.Navigation("DocentesHabilitados");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("AsignaturasHabilitadas");

                    b.Navigation("Disponibilidades");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.PlanEstudio", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
