ALTER TABLE Asignaturas
ADD COLUMN es_fija_tapsi INTEGER NOT NULL DEFAULT 0;

UPDATE Asignaturas
SET es_fija_tapsi = 1
WHERE codigo IN ('104030', '103007', '103018', '103004', '103027')
   OR UPPER(nombre) IN (
        'CÁLCULO DIFERENCIAL',
        'CALCULO DIFERENCIAL',
        'TÉCNICAS DE PROGRAMACIÓN',
        'TECNICAS DE PROGRAMACION',
        'PROGRAMACIÓN ORIENTADA A OBJETOS',
        'PROGRAMACION ORIENTADA A OBJETOS',
        'TEORÍA DE SISTEMAS',
        'TEORIA DE SISTEMAS',
        'SISTEMAS OPERATIVOS'
   );