// <auto-generated />
using System;
using ApplicationSchedule.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationSchedule.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516220320_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignacion", b =>
                {
                    b.Property<string>("IdAsignacion")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignacion");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dia");

                    b.Property<string>("Escenario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ING_DIURNA")
                        .HasColumnName("escenario");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Propuesta")
                        .HasColumnName("estado");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("IdAsignatura")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<string>("IdDocente")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("periodo");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdDocente");

                    b.ToTable("asignaciones", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignatura", b =>
                {
                    b.Property<string>("IdAsignatura")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<int>("Creditos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("creditos");

                    b.Property<bool>("EsFijaTapsi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("es_fija_tapsi");

                    b.Property<bool>("EsOpcionalTapsiDiurna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("es_opcional_tapsi_diurna");

                    b.Property<string>("IdPlan")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_plan");

                    b.Property<int>("MinEstudiantes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(15)
                        .HasColumnName("min_estudiantes");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<int>("Semestre")
                        .HasColumnType("INTEGER")
                        .HasColumnName("semestre");

                    b.HasKey("IdAsignatura");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdPlan");

                    b.ToTable("asignaturas", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Disponibilidad", b =>
                {
                    b.Property<string>("IdDisponibilidad")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_disponibilidad");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dia_semana");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_fin");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("IdDocente")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.HasKey("IdDisponibilidad");

                    b.HasIndex("IdDocente");

                    b.ToTable("disponibilidad", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Docente", b =>
                {
                    b.Property<string>("IdDocente")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("identificacion");

                    b.Property<int>("MaxAsignaturas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_asignaturas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_contrato");

                    b.HasKey("IdDocente");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("docentes", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.DocenteHabilitado", b =>
                {
                    b.Property<string>("IdDocente")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_docente");

                    b.Property<string>("IdAsignatura")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_asignatura");

                    b.Property<DateTime>("FechaHabilitacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_habilitacion");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Excel")
                        .HasColumnName("fuente");

                    b.HasKey("IdDocente", "IdAsignatura");

                    b.HasIndex("IdAsignatura");

                    b.ToTable("docentes_habilitados", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.PlanEstudio", b =>
                {
                    b.Property<string>("IdPlan")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_plan");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("jornada");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_plan");

                    b.HasKey("IdPlan");

                    b.ToTable("planes_estudio", (string)null);

                    b.HasData(
                        new
                        {
                            IdPlan = "11111111-1111-1111-1111-111111111111",
                            Jornada = "Diurna",
                            NombrePlan = "Plan de Estudios 1020 Jornada Diurna"
                        },
                        new
                        {
                            IdPlan = "22222222-2222-2222-2222-222222222222",
                            Jornada = "Nocturna",
                            NombrePlan = "Plan de Estudios Jornada Noche"
                        });
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Coordinador"
                        });
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("correo");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationSchedule.Domain.Entities.Docente", "Docente")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignatura", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.PlanEstudio", "PlanEstudio")
                        .WithMany("Asignaturas")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanEstudio");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Disponibilidad", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Docente", "Docente")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.DocenteHabilitado", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("DocentesHabilitados")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationSchedule.Domain.Entities.Docente", "Docente")
                        .WithMany("AsignaturasHabilitadas")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ApplicationSchedule.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Asignatura", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("DocentesHabilitados");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("AsignaturasHabilitadas");

                    b.Navigation("Disponibilidades");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.PlanEstudio", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("ApplicationSchedule.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
